name: Deploy to Kubernetes

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

    - name: Build and Push Docker image
      run: |
        docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/python-microservice:latest .
        docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/python-microservice:latest
